export const REGISTER_USER = 'REGISTER_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_WIZZARD_INITIAL_VALUES = 'SET_WIZZARD_INITIAL_VALUES';
export const SET_WIZZARD_ENABLED = 'SET_WIZZARD_ENABLED';
